version: '3.8'

services:
  fastapi-microservice:
    image: fastapi-back:latest
    ports:
      - "8000:8000"
    depends_on:
      - jhipster-registry

  jhipster-registry:
    image: jhipster/jhipster-registry:v7.4.0
    volumes:
      - ./central-server-config:/central-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
    ports:
      - "8761:8761"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8761/management/health']
      interval: 5s
      timeout: 5s
      retries: 20
